### ISSUE TITLE
Remove dependency on specific three.js version

### ISSUE THREAD

**Issue by rhuitl** [Wilt/three.js_triangulation#1]
I was looking into performance problems with the stock triangulation from Three.JS and found your nice project here. I tried the earcut triangulation and it is significantly faster and much more robust for polygons with lots of holes. As far as I can see, integration into Three.JS may take a while so it may make sense to make this project easier to use through bower.

I am using a different version of Three.JS (r78), whereas your bower.json declares a dependency on r75. I could fix that by blocking the dependency in ~/.bowerrc and by overriding the dependency in my bower.json, but I was wondering if you really need to declare the dependency on three.js in the first place. If you didn't, it would make integration into code that's already using Three.JS easier.

**Comment by Wilt** [comment]
_Happy to hear that you like my triangulation adapter._

I tried to read on how to use semantic versioning for three.js in my `bower.json` something in the line of:

"three.js": "https://github.com/mrdoob/three.js.git#>r75",

But sadly enough semantic versioning is currently not supported for the three.js GitHub repository. A discussion on this topic can be found here: https://github.com/mrdoob/three.js/issues/3102 
So it doesn't seem like semantic versioning will be supported in the near future.

But [there is a `resolutions` attribute for bower](http://jaketrent.com/post/bower-resolutions/) to resolve such conflicts. 
Would it be a satisfactory solution to use that;

```
{
  "name": "your project",
  "dependencies": {
    "three.js": "https://github.com/mrdoob/three.js.git#r78",
    "three.js_triangulation": "https://github.com/Wilt/three.js_triangulation.git"
  },
  "resolutions": {
    "three.js": "r78"
  }
}
```

Please let me know if this solves the problem, then I can close the issue.

**Comment by rhuitl** [comment]
Thanks for the suggestion, it seems like a very nice solution. However, I cannot get it to work because Bower will simply not report any conflicts. Without conflict, it will not apply the resolutions. So far, I could not find any information on the web if Bower is supposed to treat different GIT URIs for a dependency like "three.js" as a conflict.

**Comment by Wilt** [comment]
I tested this and it worked for me...
Is your bower in [non-interactive-mode](https://bower.io/docs/api/#non-interactive-mode)?
Your bower has to be in interactive mode otherwise it simply fails on resolution conflicts.

Try to add this line to your bower config (`.bowerrc`):

```
"interactive": true
```

**Comment by rhuitl** [comment]
My bad, you are right it works this way. I was concluding too early when I saw Bower downloading both Three.JS repositories, but apparently it needs to do that to resolve the versions. Thanks for your support, this issue can be closed.

**Comment by Wilt** [comment]
@rhuitl You are welcome. Good luck with using the adapter, if any other issues, please let me know...
